"use client";

import { Poppins } from "next/font/google";
import { usePathname } from "next/navigation";
import "./globals.css";
import AOSInit from "@/utils/AOSInit";
import BootstrapClient from "@/utils/BootstrapClient";
import GLightboxInit from "@/utils/GLightboxInit"; 
import MobileNav from "@/utils/MobileNav";
import Preloader from "@/utils/Preloader";
import ScrollHandler from "@/utils/ScrollHandler";
import ScrollTop from "@/utils/ScrollTop";
import PureCounterInit from "@/utils/PureCounterInit";
import "../style/style.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";


const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
  style: ["normal", "italic"],
  variable: "--font-poppins",
  display: "swap",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const isDashboard = pathname.startsWith("/dashboard");

  return (
    <html lang="en">
      <body className={`${poppins.variable} index-page`} >
        <BootstrapClient />
        <AOSInit />
        <Preloader />
        <GLightboxInit />
        <ScrollHandler />
        <MobileNav /> 
        <PureCounterInit />
        <ScrollTop />
        {!isDashboard && <Navbar />}
        {children}
        {!isDashboard && <Footer />}
      </body>
    </html>
  );
}
